### PR TITLE
Some changes

### PR DESCRIPTION
**Pull request by Jille**

### CODE REVIEW

**Comment by JonasJurczok** [comment]
Damn windows file system.... :)
Good spott, though.

**Comment by JonasJurczok** [comment]
Can you please also extend the README accordingly? Then I'll happily include this in 1.2.0.

**Comment by Jille** [comment]
Oops. I think I misread you. I've also bumped the version up. Want me to undo that?

**Comment by JonasJurczok** [comment]
No, no problem. I'll fix that :)

**Comment by JonasJurczok** [comment]
These typos.. -.- thanks :D

**Pull request merged**
