### PR TITLE
Feature/11 subtasks

### PR DESCRIPTION
**Pull request by JonasJurczok**
### Goal
Add subtasks to tasks

### Questions/Feedback request
Please check the layout of the tests. I'm not sure if all tests are where they should be :)

### CODE REVIEW

**Comment by JonasJurczok** [comment]
@hoylemd @Tarrke It's finished. Feel free to take a look :)

**Comment by Tarrke** [comment]
I did looked into this when you opened it. I just have one word: OMG! Nice.

I'll comment further sunday I think i'll have a bit of time to do that.

**Comment by JonasJurczok** [comment]
Awesome, thanks :)
I would love to release it Sunday evening, but next week is also fine.

**Comment by JonasJurczok** [comment]
Hey @Tarrke 
I would like to merge and release this. Did you find any showstoppers? :)

I also added a small fix for https://mods.factorio.com/mod/Todo-List/discussion/5bf9e5316d2df8000c53bab4 here. Apparently there are some migration problems for older versions...

**Comment by hoylemd** [comment]
I'm not sure when I'll have time to give this real attention.  November/december are very busy times.  I haven't even gotten to finishing reviewing the big refactor :/

**Comment by JonasJurczok** [comment]
No worries. I'm also happy about "you messed up in line 234" tickets at any
point in time :)

I would merge this the to solve the attached problem and await your
feedback later :)

**Comment by JonasJurczok** [comment]
No worries. It's open source.. no obligation :)
Enjoy your time.

**Comment by Tarrke** [comment]
Hi guys,

so sorry for being this late. I've rewied and there is no showstoppers in it.

On a side note, my Angel & SpaceX game is in the latest part, and I'll re-use Todo-List in a from scratch game with all these nex features, I'm looking forward to it :).

**Comment by JonasJurczok** [comment]
Nice :)

**Pull request merged**
