### PR TITLE
Fr locale

### PR DESCRIPTION
**Pull request by Tarrke**
I made a locale for French language.

I did had to correct the release.py script, the zip file generated did not contained any lua file. It is good runinng under python 3.5, if you prefer a python 2.7 version just tell me I'll make some arrangements to the glob.glob call.

### CODE REVIEW

**Comment by Tarrke** [comment]
Please ignore if possible the last commit about release.py I'll open a new merge request ofr that.

**Comment by JonasJurczok** [comment]
Hi,
the other PR has been merged. The easiest way is if you [rebase](https://git-scm.com/docs/git-rebase) your changes on the updated master.

Regarding the release.py.... I also don't use it anymore. For general mod handling and packaging stuff I finally got [faketorio](https://github.com/jonasjurczok/faketorio) to a usable state :)
running faketorio build will produce a folder that you just have to zip and then you are done :)

**Comment by Tarrke** [comment]
Ho crap, I opened a new PR with my new master branch as it has the right stuff, I hope. Sorry I'm not really used to github and this stuff while working with a fork really.

**Comment by JonasJurczok** [comment]
Closing because issue was resolved in other PR.

**Pull request closed without merging**
